# Generated by Django 4.1.2 on 2022-10-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitcdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cdn_path',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
